--
-- File generated with SQLiteStudio v3.2.1 on ter mai 11 00:48:57 2021
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: CLIENTE
CREATE TABLE CLIENTE (CODIGO INTEGER PRIMARY KEY UNIQUE NOT NULL, NOME VARCHAR (100) NOT NULL, CPF_CNPJ VARCHAR (25) NOT NULL UNIQUE, RG_IE VARCHAR (20) UNIQUE NOT NULL, TIPO_PESSOA CHAR (1) NOT NULL, DATA_CADASTRO DATE, ATIVO CHAR (1) NOT NULL);

-- Table: ENDERECO
CREATE TABLE ENDERECO (CODIGO INTEGER PRIMARY KEY UNIQUE NOT NULL, LOGRADOURO VARCHAR (100) NOT NULL, NUMERO INTEGER (10) NOT NULL, CEP INTEGER (20) NOT NULL, BAIRRO VARCHAR (50) NOT NULL, CIDADE VARCHAR (80) NOT NULL, UF CHAR (2) NOT NULL, PAIS VARCHAR (50) NOT NULL, CODIGO_CLIENTE INTEGER REFERENCES CLIENTE (CODIGO));

-- Table: TELEFONE
CREATE TABLE TELEFONE (CODIGO INTEGER PRIMARY KEY UNIQUE NOT NULL, TELEFONE VARCHAR (20) NOT NULL, CONTATO VARCHAR (50), CODIGO_CLIENTE INTEGER REFERENCES CLIENTE (CODIGO));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
